README.md
The instructions now match what I had to do to get a build to work.
=> Updated build instructions to match discovered behavior

pds_reading.cc
This should have been updated as part of the unrolled work.
=> Fix assert in pds_reader.cc

CMakeLists.txt, PDSOutputer.cc, PDSOutputer.h, RootEventOutputer.cc, RootEventOutputer.h, pds_common.h, pds_reading.h, pds_writer.cc, pds_writer.h
Created common enums
Moved compression to standalone functions
=> Refactored PDS code

CMakeLists.txt, PDSOutputer.cc, RootEventOutputer.cc, pds_common.cc, pds_common.h
- Common function to handle parsing parameter arguments
- Common function to get name for compression algorithms
=> Share more code between PDS and RootEvent classes

CMakeLists.txt, HDFCxx.h, HDFEventOutputer.cc, HDFEventOutputer.h
=> added event blob based format for HDF5

HDFEventOutputer.cc, HDFEventOutputer.h
Also fixed a few bugs.
Still need to added compression algorithm name to file.
=> Added compression to HDFEventOutputer

HDFOutputer.cc, HDFOutputer.h
Also fixed the last batch not being written bug.
=> Added configurable chunkSize to HDFOutputer

CMakeLists.txt, HDFBatchEventsOutputer.cc, HDFBatchEventsOutputer.h, HDFEventOutputer.cc, README.md, RepeatingRootSource.cc, RepeatingRootSource.h
Added some additional improvements and bug fixes.
=> Added HDFBatchEventsOutputer

RootOutputer.cc, RootOutputer.h
Capture how long it takes to do the final Write and Close calls.
=> Record end of job time for RootOutputer

CMakeLists.txt, EventUnevenSleepWaiter.cc, README.md
Allows controlling how much parallelization to use within an Event while doing the wait.
=> Added EventUnevenSleepWaiter

RootOutputer.cc, RootOutputer.h, RootOutputerConfig.cc, RootOutputerConfig.h, TBufferMergerRootOutputer.h
Resubmit PR accidentally closed
=> Add TFileCacheWrite and make cacheSize an option for ROOTOutputer.

RootOutputer.cc, RootOutputer.h, RootOutputerConfig.cc, RootOutputerConfig.h, TBufferMergerRootOutputer.cc, TBufferMergerRootOutputer.h
Resubmit of https://github.com/hep-cce2/root_serialization/pull/42 for code review after resetting head of master
=> Add TFileCacheWrite and make cacheSize an option for ROOTOutputer

README.md, RootOutputer.cc, RootOutputer.h, RootOutputerConfig.cc, RootOutputerConfig.h, TBufferMergerRootOutputer.cc, TBufferMergerRootOutputer.h
Resubmit of https://github.com/hep-cce2/root_serialization/pull/44 for code review after resetting head of master
=> Add TFileCacheWrite and make cacheSize an option for ROOTOutputer  and TBufferMergerROOTOutputer

SharedPDSSource.cc
For some reason the destructor for the lambda passed to the queue is not being called so the OptionalTaskHolder is never released. Explicitly moving it to a local variable guarantees the destructor will be called.
=> SharedPDSSource properly stops if try to read too many events

RNTupleOutputer.h, SerialRNTupleSource.h
Not sure what version of ROOT i'm supposed to target.  root@master has made a few api changes, which I've attempted to track with this pull request.
Review requested of the RNTupleView change -- wasn't sure which boolean value to use there.
=> updates for root master api changes

CMakeLists.txt, RNTupleTFileOutputer.cc, RNTupleTFileOutputer.h, SerialRNTupleRetrievers.cc, SerialRNTupleRetrievers.h, SerialRNTupleTFileSource.cc, SerialRNTupleTFileSource.h
Added code that explicitly uses a TFile as the storage for an RNTuple. This mimics more closely how we expect frameworks to interact with RNTuple.
=> Added RNTuple writing/reading to/from a TFile

CMakeLists.txt, README.md, RNTupleParallelOutputer.cc, RNTupleParallelOutputer.h
This uses a RNTupleParallelWriter per lane to accommodate concurrent writing of lanes.
=> Added RNTupleParallelOutputer

common_unrolling.cc
=> Update to change in ROOT TClass interface

RNTupleOutputer.cc, RNTupleTFileOutputer.cc
Attempt to decrease memory usage.
=> Use RNTupleModel::CreateBare

RNTupleOutputer.cc, RNTupleOutputerConfig.cc, RNTupleOutputerConfig.h
Added the new RNTupleWriter configuration options and the ability to print the estimated memory usage.
=> Added additional optimization parameters to RNTupleOutputer

SerialRNTupleTFileSource.cc
This matches a change in ROOT master as of 07/17/2024
=> Update to new RNTupleReader::Open interface

CMakeLists.txt, README.md, RNTupleAsyncOutputer.cc, RNTupleAsyncOutputer.h, RNTupleParallelOutputer.cc, SerialRNTupleRetrievers.cc, SerialRNTupleRetrievers.h, SerialRNTupleSource.cc, SerialRNTupleSource.h, SerialRNTupleTFileSource.cc, SerialRNTupleTFileSource.h
- This tests the FillNoFlush/FlushCluster API
- Also updated more of the code to the most recent RNTuple API changes
=> Added RNTupleAsyncOutputer
